name: Generate Snake Game

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Generate Snake Game from activity data
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: StephaniMiler

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Generate Snake Game animation" || exit 0
          git push

