name: Generate Snake Game

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Generate Snake Game from activity data
        uses: Platane/snk@v2
        with:
          github_user_name: StephaniMiler
          outputs: dist/snake.svg

      - name: Push generated Snake Game to the output branch
        uses: actions/upload-artifact@v3
        with:
          path: dist/snake.svg
