name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código Snake Game
        uses: Platane/snk@master
        with:
          github_user_name: StephaniMiler
          outputs: dist/github-user-contribution.svg
      - name: Commitar e publicar
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          keep_files: true
